rework NGINX reverse proxy docs to support CODE
nextcloud/all-in-one pull request #1313
Opened 2022-10-26 10:31 UTC by TheManchineel

As per PR #1236, applied the same documentation change to the NGINX configuration, so as to pass the full URI of each HTTP request to the Collabora Online backend. This fixes #834 but for NGINX rather than Apache. It might be necessary to make similar changes to other proxy software, but NGINX is what I am familiar with.

Signed-off-by: TheManchineel <37479927+TheManchineel@users.noreply.github.com>

2022-10-26 10:52 UTC, szaimen requested changes
Thanks for your PR! One small change and then I'll merge!

2022-10-26 10:52 UTC, szaimen commented on reverse-proxy.md
> -
Lets keep this

2022-10-26 11:13 UTC, TheManchineel commented
> Thanks for your PR! One small change and then I'll merge!

Fair, the reason I removed the line was that the same had been done to the Apache config section

2022-10-26 13:01 UTC, Zoey2936 commented
> > Thanks for your PR! One small change and then I'll merge!
> 
> Fair, the reason I removed the line was that the same had been done to the Apache config section

The line still exists: https://github.com/nextcloud/all-in-one/blob/ab7c2fccad866893ab10286317a207e66c490836/reverse-proxy.md?plain=1#L24
Only the linked Issue was removed from this line

2022-10-26 14:53 UTC, TheManchineel commented
@Zoey2936 oops, oh well, I'm definitely tired

2022-10-26 14:58 UTC, Zoey2936 commented
Can you please re-add this line?

2022-10-27 10:36 UTC, szaimen commented
> Can you please re-add this line?

@TheManchineel yes, can you please do so?

2022-10-27 10:53 UTC, TheManchineel commented
@szaimen Sorry, I'm rather new to amending commits on GitHub pull requests. Does it look correct now?

2022-10-27 10:55 UTC, szaimen commented
> @szaimen Sorry, I'm rather new to amending commits on GitHub pull requests. Does it look correct now?

yes, looks good! Thanks!

2022-10-27 10:55 UTC, szaimen approved these changes

2022-10-27 10:57 UTC, merged