redis: add hint to wiki if overcommit disabled
nextcloud/all-in-one pull request #1732
Opened 2023-01-12 19:22 UTC by ManOki

You may see a warning by redis like `WARNING Memory overcommit must be enabled! Without it, a background save or replication may fail under low memory condition.`

In this case you have to enable vm.overcommit on your host machine (cannot be done by docker/redis), so this PR links to a discussion with commands and background information if vm.overcommit is disabled.

2023-01-12 19:29 UTC, Zoey2936 requested changes

2023-01-12 19:29 UTC, Zoey2936 commented on Containers/redis/start.sh
> +if [[ $(sysctl -n vm.overcommit_memory)  != "1" ]]; then
```suggestion
if [ "$(sysctl -n vm.overcommit_memory)" != "1" ]; then
```

2023-01-12 19:29 UTC, Zoey2936 commented on Containers/redis/start.sh
> +    echo Memory overcommit is disabled but necessary for safe operation
```suggestion
    echo "Memory overcommit is disabled but necessary for safe operation"
```

2023-01-12 19:29 UTC, Zoey2936 commented on Containers/redis/start.sh
> +    echo See https://github.com/nextcloud/all-in-one/discussions/1731 how to enable overcommit
```suggestion
    echo "See https://github.com/nextcloud/all-in-one/discussions/1731 how to enable overcommit"
```

2023-01-12 19:44 UTC, Zoey2936 commented
I don't know, but maybe this should also be mentioned also somewhere outside the Redis container logs
And I hope this is no problem for you, but I've edited your discussion comment a bit

2023-01-12 19:52 UTC, ManOki commented
> maybe this should also be mentioned also somewhere outside the Redis container logs

Yes, I agree. But I do not know exactly where is the best place. Maybe you can add a hint in mastercontainer (while setup). As you have [seen ](https://github.com/nextcloud/all-in-one/pull/1732/files#diff-431d00898671d8860c780d0f07baab8600a4ea0cd89d9448b218658b475b520eR4) docker containers are able to read the setting of the host system via `sysctl -n vm.overcommit_memory`.

> I've edited your discussion comment a bit

Feel free, you are much more advanced in AIO than me ;)

2023-01-12 22:28 UTC, szaimen commented
>> maybe this should also be mentioned also somewhere outside the Redis container logs
>
> Yes, I agree. But I do not know exactly where is the best place. Maybe you can add a hint in mastercontainer (while setup). 

Since redis is only used as cache, I don't think that it is important enough to mention it in the mastercontainer. Only showing it in the redis container is fine, imho.

2023-01-12 22:33 UTC, szaimen approved these changes
LGTM. Thank you Zoey and @ManOki! :)

2023-01-12 22:33 UTC, merged

2023-01-12 22:36 UTC, szaimen commented
Btw, @ManOki, I just added you as contributor to this repo since you've created quite a few PRs already and I think it would make things easier when you have write permission on the repo :)

2023-01-13 08:20 UTC, ManOki commented
> I just invited you as contributor to this repo since you've created quite a few PRs already and I think it would make things easier when you have write permission on the repo :)

Thank you! And thanks for approval.

2023-01-17 13:15 UTC, szaimen commented
This is now released with v4.2.0 Beta. Testing and feedback is welcome! See https://github.com/nextcloud/all-in-one#how-to-switch-the-channel