apache healthcheck, check localhost apacheport with every apache port
nextcloud/all-in-one pull request #2302
Opened 2023-04-08 11:28 UTC by Zoey2936

2023-04-08 23:22 UTC, szaimen commented
Thanks Zoey! Is there a reason for this change?

2023-04-09 05:14 UTC, Zoey2936 commented
> Thanks Zoey! Is there a reason for this change?

No... But I thought that localhost can be checked every time

2023-04-09 08:03 UTC, Zoey2936 commented
Other question, AIO only supports offially port 443, what about also alwas checking port 443 from external?

2023-04-10 12:08 UTC, szaimen commented
> Other question, AIO only supports offially port 443, what about also alwas checking port 443 from external?

That would basically mean that the healthcheck would break behind cloudflare, IIRC?

2023-04-10 12:08 UTC, szaimen commented
> > Thanks Zoey! Is there a reason for this change?
> 
> No... But I thought that localhost can be checked every time

Does this have any benefit? (I mean if the domain and 443 works, the container should be healthy, no?

2023-04-10 15:06 UTC, Zoey2936 commented
> 

why should it break? cloudflare has port 443 open

2023-04-10 15:06 UTC, Zoey2936 commented
> > > Thanks Zoey! Is there a reason for this change?
> > 
> > 
> > No... But I thought that localhost can be checked every time
> 
> Does this have any benefit? (I mean if the domain and 443 works, the container should be healthy, no?

if it runs behind cloudflare the port is open, but the apache container could be stopped

2023-04-10 15:18 UTC, szaimen commented
> > 
> 
> why should it break? cloudflare has port 443 open

In the past were connection attempts blocked by cloudflare... but you are probably right because this only checks if a tcp connection is possible which is likely not blocked by cloudflare.

2023-04-10 15:19 UTC, szaimen commented
However what about scenarios where like when using dns challenge where the port will not be opened?

2023-04-10 15:20 UTC, szaimen approved these changes
Fine by me in the current form

2023-04-10 15:30 UTC, Zoey2936 commented
> However what about scenarios where like when using dns challenge where the port will not be opened?

you mean in local instances? even they need to have port 443 open and the nextcloud domain should point to the domain

2023-04-10 15:40 UTC, szaimen commented
> you mean in local instances? even they need to have port 443 open and the nextcloud domain should point to the domain

True. Okay then lets always check it

2023-04-11 08:34 UTC, szaimen requested changes

2023-04-11 08:34 UTC, szaimen commented on Containers/apache/healthcheck.sh
> +nc -z "$NC_DOMAIN" "$APACHE_PORT" || exit 1
```suggestion
nc -z "$NC_DOMAIN" 443 || exit 1
```

2023-04-11 09:36 UTC, szaimen approved these changes

2023-04-14 12:56 UTC, merged

2023-04-15 17:52 UTC, szaimen commented
This is now released with v4.9.0 Beta. Testing and feedback is welcome! See https://github.com/nextcloud/all-in-one#how-to-switch-the-channel