Allow networks to be created pre-emptively
nextcloud/all-in-one pull request #3129
Opened 2023-08-10 05:09 UTC by jennydaman

Currently, `nextcloud-aio-mastercontainer` will crash if the `nextcloud-aio` network already exists. This PR changes the behavior so that the `nextcloud-aio` network may be created preemptively.

I did this as a workaround to a bug in rootless Podman: https://github.com/containers/podman/issues/19577

2023-08-10 06:49 UTC, szaimen requested changes
Thanks for the PR, however podman should return error code 409 if the network already exists. See https://github.com/containers/podman/issues/15499 and https://github.com/nextcloud/all-in-one/blob/e8ab2c702687e2f87895f076af0f5c961851bb9e/php/src/Docker/DockerActionManager.php#L780

2023-08-10 06:50 UTC, closed without merging

2023-08-10 06:57 UTC, jennydaman commented
This patch is needed for Nextcloud-AIO to work with Podman version 4.6.0. The most recent reply to https://github.com/containers/podman/issues/15499 was 7 months ago, yet no related change has landed in Podman yet.

If my setup breaks in the future, would you like me to submit another PR?

2023-08-10 06:59 UTC, szaimen commented
Can you tell which error code is returned if the network already exists? Before the bug was fixed it was 500 if I remember correctly. Now it should in theory be 409 but apparently it is not...

2023-08-10 07:18 UTC, jennydaman commented
```patch
diff --git a/php/src/Docker/DockerActionManager.php b/php/src/Docker/DockerActionManager.php
index 93abcdc..a3350d6 100644
--- a/php/src/Docker/DockerActionManager.php
+++ b/php/src/Docker/DockerActionManager.php
@@ -788,7 +788,8 @@ class DockerActionManager
                 $responseBody = json_decode((string)$response->getBody(), true);
                 $connectedNetworks = $responseBody['NetworkSettings']['Networks'];
                 if (array_key_exists($network, $connectedNetworks)) {
-                    return;
+                    error_log(sprintf("IAMHERE: THE ERROR IS %s", $e));
+                    //return;
                 }
             } catch (RequestException $e) {
                 // do nothing
```


<details>
<summary>logs</summary>

```
Aug 10 03:14:52 ferritin podman[97425]: time="2023-08-10T03:14:52-04:00" level=info msg="Request Failed(Conflict): network name nextcloud-aio already used: network already exists"Aug 10 03:14:52 ferritin podman[97425]: @ - - [10/Aug/2023:03:14:52 -0400] "POST /v1.41/networks/create HTTP/1.1" 409 126 "" "GuzzleHttp/7"Aug 10 03:14:52 ferritin podman[97425]: @ - - [10/Aug/2023:03:14:52 -0400] "GET /v1.41/containers/nextcloud-aio-mastercontainer/json HTTP/1.1" 200 9047 "" "GuzzleHttp/7"Aug 10 03:14:52 ferritin nextcloud-aio-mastercontainer[96945]: NOTICE: PHP message: IAMHERE: THE ERROR IS GuzzleHttp\Exception\ClientException: Client error: `POST http://localhost/v1.41/networks/create` resulted in a `409 Conflict` response:Aug 10 03:14:52 ferritin nextcloud-aio-mastercontainer[96945]: {"cause":"network already exists","message":"network name nextcloud-aio already used: network already exists","response" (truncated...)Aug 10 03:14:52 ferritin nextcloud-aio-mastercontainer[96945]:  in /var/www/docker-aio/php/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:113Aug 10 03:14:52 ferritin nextcloud-aio-mastercontainer[96945]: Stack trace:Aug 10 03:14:52 ferritin nextcloud-aio-mastercontainer[96945]: #0 /var/www/docker-aio/php/vendor/guzzlehttp/guzzle/src/Middleware.php(72): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response), NULL, Array, NULL)Aug 10 03:14:52 ferritin nextcloud-aio-mastercontainer[96945]: #1 /var/www/docker-aio/php/vendor/guzzlehttp/promises/src/Promise.php(209): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Response))Aug 10 03:14:52 ferritin podman[97425]: time="2023-08-10T03:14:52-04:00" level=info msg="Request Failed(Internal Server Error): container c7739a6568dc622696883126dba4eb3127d4e99952d8ca9faf164f1b30ac889f is already connected to network \"nextcloud-aio\": network is already connected"Aug 10 03:14:52 ferritin podman[97425]: @ - - [10/Aug/2023:03:14:52 -0400] "POST /v1.41/networks/nextcloud-aio/connect HTTP/1.1" 500 223 "" "GuzzleHttp/7"Aug 10 03:14:52 ferritin nextcloud-aio-mastercontainer[96945]: #2 /var/www/docker-aio/php/vendor/guzzlehttp/promises/src/Promise.php(158): GuzzleHttp\Promise\Promise::callHandler(1, Object(GuzzleHttp\Psr7\Response), NULL)Aug 10 03:14:52 ferritin nextcloud-aio-mastercontainer[96945]: #3 /var/www/docker-aio/php/vendor/guzzlehttp/promises/src/TaskQueue.php(52): GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closure}()Aug 10 03:14:52 ferritin nextcloud-aio-mastercontainer[96945]: #4 /var/www/docker-aio/php/vendor/guzzlehttp/promises/src/Promise.php(251): GuzzleHttp\Promise\TaskQueue->run(true)Aug 10 03:14:52 ferritin nextcloud-aio-mastercontainer[96945]: #5 /var/www/docker-aio/php/vendor/guzzlehttp/promises/src/Promise.php(227): GuzzleHttp\Promise\Promise->invokeWaitFn()Aug 10 03:14:52 ferritin nextcloud-aio-mastercontainer[96945]: #6 /var/www/docker-aio/php/vendor/guzzlehttp/promises/src/Promise.php(272): GuzzleHttp\Promise\Promise->waitIfPending()Aug 10 03:14:52 ferritin nextcloud-aio-mastercontainer[96945]: #7 /var/www/docker-aio/php/vendor/guzzlehttp/promises/src/Promise.php(229): GuzzleHttp\Promise\Promise->invokeWaitList()Aug 10 03:14:52 ferritin nextcloud-aio-mastercontainer[96945]: #8 /var/www/docker-aio/php/vendor/guzzlehttp/promises/src/Promise.php(69): GuzzleHttp\Promise\Promise->waitIfPending()Aug 10 03:14:52 ferritin nextcloud-aio-mastercontainer[96945]: #9 /var/www/docker-aio/php/vendor/guzzlehttp/guzzle/src/Client.php(189): GuzzleHttp\Promise\Promise->wait()Aug 10 03:14:52 ferritin nextcloud-aio-mastercontainer[96945]: #10 /var/www/docker-aio/php/src/Docker/DockerActionManager.php(766): GuzzleHttp\Client->request('POST', 'http://localhos...', Array)Aug 10 03:14:52 ferritin nextcloud-aio-mastercontainer[96945]: #11 /var/www/docker-aio/php/src/Docker/DockerActionManager.php(822): AIO\Docker\DockerActionManager->ConnectContainerIdToNetwork('nextcloud-aio-m...', '')Aug 10 03:14:52 ferritin nextcloud-aio-mastercontainer[96945]: #12 /var/www/docker-aio/php/public/index.php(80): AIO\Docker\DockerActionManager->ConnectMasterContainerToNetwork()Aug 10 03:14:52 ferritin nextcloud-aio-mastercontainer[96945]: #13 /var/www/docker-aio/php/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(38): Closure->{closure}(Object(GuzzleHttp\Psr7\ServerRequest), Object(GuzzleHttp\Psr7\Response), Array)Aug 10 03:14:52 ferritin nextcloud-aio-mastercontainer[96945]: #14 /var/www/docker-aio/php/vendor/slim/slim/Slim/Routing/Route.php(358): Slim\Handlers\Strategies\RequestResponse->__invoke(Object(Closure), Object(GuzzleHttp\Psr7\ServerRequest), Object(GuzzleHttp\Psr7\Response), Array)Aug 10 03:14:52 ferritin nextcloud-aio-mastercontainer[96945]: #15 /var/www/docker-aio/php/vendor/slim/slim/Slim/MiddlewareDispatcher.php(65): Slim\Routing\Route->handle(Object(GuzzleHttp\Psr7\ServerRequest))Aug 10 03:14:52 ferritin nextcloud-aio-mastercontainer[96945]: #16 /var/www/docker-aio/php/vendor/slim/slim/Slim/MiddlewareDispatcher.php(65): Slim\MiddlewareDispatcher->handle(Object(GuzzleHttp\Psr7\ServerRequest))Aug 10 03:14:52 ferritin nextcloud-aio-mastercontainer[96945]: #17 /var/www/docker-aio/php/vendor/slim/slim/Slim/Routing/Route.php(315): Slim\MiddlewareDispatcher->handle(Object(GuzzleHttp\Psr7\ServerRequest))Aug 10 03:14:52 ferritin nextcloud-aio-mastercontainer[96945]: #18 /var/www/docker-aio/php/vendor/slim/slim/Slim/Routing/RouteRunner.php(68): Slim\Routing\Route->run(Object(GuzzleHttp\Psr7\ServerRequest))Aug 10 03:14:52 ferritin nextcloud-aio-mastercontainer[96945]: #19 /var/www/docker-aio/php/vendor/slim/csrf/src/Guard.php(476): Slim\Routing\RouteRunner->handle(Object(GuzzleHttp\Psr7\ServerRequest))Aug 10 03:14:52 ferritin nextcloud-aio-mastercontainer[96945]: #20 /var/www/docker-aio/php/vendor/slim/slim/Slim/MiddlewareDispatcher.php(168): Slim\Csrf\Guard->process(Object(GuzzleHttp\Psr7\ServerRequest), Object(Slim\Routing\RouteRunner))Aug 10 03:14:52 ferritin nextcloud-aio-mastercontainer[96945]: #21 /var/www/docker-aio/php/vendor/slim/twig-view/src/TwigMiddleware.php(115): Psr\Http\Server\RequestHandlerInterface@anonymous->handle(Object(GuzzleHttp\Psr7\ServerRequest))Aug 10 03:14:52 ferritin nextcloud-aio-mastercontainer[96945]: #22 /var/www/docker-aio/php/vendor/slim/slim/Slim/MiddlewareDispatcher.php(121): Slim\Views\TwigMiddleware->process(Object(GuzzleHttp\Psr7\ServerRequest), Object(Psr\Http\Server\RequestHandlerInterface@anonymous))Aug 10 03:14:52 ferritin nextcloud-aio-mastercontainer[96945]: #23 /var/www/docker-aio/php/src/Middleware/AuthMiddleware.php(38): Psr\Http\Server\RequestHandlerInterface@anonymous->handle(Object(GuzzleHttp\Psr7\ServerRequest))Aug 10 03:14:52 ferritin nextcloud-aio-mastercontainer[96945]: #24 /var/www/docker-aio/php/vendor/slim/slim/Slim/MiddlewareDispatcher.php(269): AIO\Middleware\AuthMiddleware->__invoke(Object(GuzzleHttp\Psr7\ServerRequest), Object(Psr\Http\Server\RequestHandlerInterface@anonymous))Aug 10 03:14:52 ferritin nextcloud-aio-mastercontainer[96945]: #25 /var/www/docker-aio/php/vendor/slim/slim/Slim/Middleware/ErrorMiddleware.php(76): Psr\Http\Server\RequestHandlerInterface@anonymous->handle(Object(GuzzleHt [...]

2023-08-10 07:20 UTC, szaimen commented
No I meant what error code is thrown here if the network should already exist?
https://github.com/nextcloud/all-in-one/blob/e8ab2c702687e2f87895f076af0f5c961851bb9e/php/src/Docker/DockerActionManager.php#L781

2023-08-10 07:24 UTC, jennydaman commented
`$e` is caught and printed out by

```php
error_log(sprintf("IAMHERE: THE ERROR IS %s", $e));
```

The specific log line is

```
IAMHERE: THE ERROR IS GuzzleHttp\Exception\ClientException: Client error: `POST http://localhost/v1.41/networks/create` resulted in a `409 Conflict` response:Aug 10 03:14:52 ferritin nextcloud-aio-mastercontainer[96945]: {"cause":"network already exists","message":"network name nextcloud-aio already used: network already exists","response" (truncated...)
```

2023-08-10 07:26 UTC, szaimen commented
Ah I see. However since the error code is 409, AIO should not throw, right?

2023-08-10 07:37 UTC, jennydaman commented
That is correct.

Since the error code is 409, `$e` is caught and not thrown again, and execution proceeds to the code I added which handles the pre-existing network.

2023-08-10 07:45 UTC, szaimen commented
This is what I am wondering about: if the network already exists, it should return 409 and then not throw an error anymore. So why does it do on podman but not on docker?

2023-08-10 07:48 UTC, jennydaman commented
Oh, I left out some information. My bad.

The error with network creation is handled correctly, however the error fails later on here:

https://github.com/nextcloud/all-in-one/blob/e8ab2c702687e2f87895f076af0f5c961851bb9e/php/src/Docker/DockerActionManager.php#L785-L803

This is because of the linked Podman bug: https://github.com/containers/podman/issues/19577

2023-08-10 07:51 UTC, szaimen commented
> This is because of the linked Podman bug: [containers/podman#19577](https://github.com/containers/podman/issues/19577)

Ah I see. Since this apparently is a Podman bug, I would rather not like to merge your change into AIO as podman is not supported by us anyway.

2025-02-25 23:43 UTC, rugk commented
Just as a reader from the future, https://github.com/containers/podman/issues/19577 is not fixed as they seem to think stuff is different?

As far from what I read, `Network=bridge` should fix it though, should not it?