Update reverse-proxy.md
nextcloud/all-in-one pull request #4170
Opened 2024-02-03 12:32 UTC by SuitDeer

I have added a small explenation on how you need to use the `network_mode:  host` option if you use the nginx-proxy-manager as a container on the same machine as the nextcloud-aio container.

I know that it is explainded in point 1. of this document but it was very hidden.

2024-02-11 21:41 UTC, Zoey2936 requested changes
the sample compose file is invalid

2024-02-12 11:21 UTC, SuitDeer commented
Hi @Zoey2936 
in my merge request I have used the official compose of the nginx-proxy-manager [https://nginxproxymanager.com/guide/#quick-setup](https://nginxproxymanager.com/guide/#quick-setup) 

I have only added the line `network_mode: host`

I think it is a valid YAML docker-compose file:
[https://codebeautify.org/yaml-validator/cbccd63a](https://codebeautify.org/yaml-validator/cbccd63a)

What exacly does not work in my added docker-compose code block?

2024-02-12 12:28 UTC, Zoey2936 commented
invalid yaml file != invalid compose file
you can't combine ports and network_mode: host

2024-02-12 12:30 UTC, Zoey2936 commented on reverse-proxy.md
> +```
```suggestion
Following example shows how to implement the `network_mode: host` option into the nginx-proxy-manager compose.yaml file:

```yaml
services:
  nginx-proxy-manager:
    container_name: nginx-proxy-manager
    image: jc21/nginx-proxy-manager:latest
    restart: always
    network_mode: host
    volumes:
      - "/opt/npm:/data"
      - "/opt/npm-letsencrypt:/etc/letsencrypt"
    environment:
      - "TZ=Europe/Berlin"
```

2024-02-12 12:37 UTC, Zoey2936 commented on reverse-proxy.md
> +      - "TZ=Europe/Berlin"
sorry I removed this
```suggestion
      - "TZ=Europe/Berlin"
```
```

2024-02-12 12:39 UTC, Zoey2936 approved these changes

2024-03-04 10:32 UTC, szaimen commented
I am not sure about this change. Wouldn't we in theory also need to add examples for all other reverse proxies if we merge this change here?

2024-04-08 18:27 UTC, closed without merging