Add private mirror support for OCI references #4362
nextcloud/all-in-one pull request #4363
Opened 2024-03-11 21:49 UTC by elysweyr

Implements #4362

2024-03-11 21:58 UTC, Zoey2936 commented on nextcloud-aio-helm-chart/templates/nextcloud-aio-apache-deployment.yaml
> +              value: "{{ .Values.NC_DOMAIN }}"FF
is there a reason for this "FF"?

2024-03-11 21:59 UTC, Zoey2936 requested changes
I think you need to edit this file: https://github.com/nextcloud/all-in-one/blob/main/nextcloud-aio-helm-chart/update-helm.sh because the helm-chart is generated using this script your changes will be removed again with the next run of this script

2024-03-11 22:36 UTC, elysweyr commented
> I think you need to edit this file: https://github.com/nextcloud/all-in-one/blob/main/nextcloud-aio-helm-chart/update-helm.sh because the helm-chart is generated using this script your changes will be removed again with the next run of this script

@Zoey2936 
Updated `update-helm.sh` and refined my control flow in case `ALPINE_IMAGE_ORG` and `IMAGE_MIRROR_PREFIX` are unset which would have lead to `/alpine` but if fixed now.

2024-03-11 22:37 UTC, elysweyr commented on nextcloud-aio-helm-chart/templates/nextcloud-aio-apache-deployment.yaml
> +              value: "{{ .Values.NC_DOMAIN }}"FF
My bad

2024-03-13 13:16 UTC, szaimen commented
Hi, have you tested if this actually works? Because I doubt it. See https://github.com/nextcloud/all-in-one/discussions/4362#discussioncomment-8773102

2024-03-14 11:41 UTC, szaimen commented
Hi @elysweyr I just gave you write access to the repo and pushed your changes to https://github.com/nextcloud/all-in-one/pull/4387 so that all workflows work. Lets continue there.

2024-03-14 11:41 UTC, closed without merging