DockerActionManager: fix getting the tag from the image
nextcloud/all-in-one pull request #5503
Opened 2024-10-31 12:14 UTC by szaimen

2024-11-02 08:05 UTC, docjyJ requested changes

2024-11-04 20:09 UTC, szaimen commented on php/src/Docker/DockerActionManager.php
> +            if (isset($tagArray[1])) {
Thanks, good point! :)

2024-11-06 11:59 UTC, szaimen commented
Thanks for the review @docjyJ 😊

2024-11-06 11:59 UTC, merged

2024-11-07 14:48 UTC, szaimen commented
This is now released with v9.9.0 Beta. Testing and feedback is welcome! See https://github.com/nextcloud/all-in-one#how-to-switch-the-channel